### ISSUE TITLE
using the existing app configuration

### ISSUE THREAD

**Issue by afeld** [contraband/autopilot#11]
Hey! Pleased to have come across this project. I had written [something similar](https://github.com/18F/cf-blue-green), which I had been [planning to port over to a CLI plugin](https://github.com/18F/cf-blue-green/issues/2).

Wanted to raise an idea: while I totally understand the reasoning for (and simplicity of) requiring the user to have a complete manifest to deploy with, my guess is that in reality, there are lots of applications that don't (mine included). For `cf-blue-green`, I was starting to play around with having the local manifest merged with the remote one (basically `local -> inherit: -> remote`); in other words, any local manifest changes will be included in the new deploy, but any configuration _not_ reflected in the manifest would be included as well.

Not sure how well I explained it... Thoughts? Also, sorry if there's a better forum for feature ideas.

/cc @mogul @dhcole

**Comment by adelevie** [comment]
@afeld what does it mean for a manifest to be "complete"? How can I verify this on my own manifests?

**Comment by afeld** [comment]
@adelevie I mean that deploying with the same codebase+manifest to a new application (in the Cloud Foundry sense) will yield the same results. For example, if an API secret is set as a user-provided environment variable (rather than, say, a [user-provided service instance](https://docs.cloudfoundry.org/devguide/services/user-provided.html) and bound within the manifest), deploying to a new application would not have access to that secret. In other words, the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) would suggest that deploying an application with Autopilot to yield the same results as deploying with `cf push`, regardless of what is stated in the manifest vs. previously set through the command line.

Not sure that I'm explaining it well...?

**Comment by afeld** [comment]
I have come around in deciding that, while this might be convenient for switching to autopilot, it's actually an antipattern.
