### ISSUE TITLE
Secondary routes not getting mapped

### ISSUE THREAD

**Issue by sgpivotal** [contraband/autopilot#13]
Hi,

I have noticed that if you have multiple routes mapped to your app that only the primary route gets re-mapped. This could lead to downtime for anyone accessing the app on any routes other than the primary route. This is a particular issue if you have a secondary route to your app mapped as "www".

There is also an orphaned route left after running cf zero-downtime-push.

Regards,
S

**Comment by xoebus** [comment]
Is it possible to put multiple routes in the manifest?

**Comment by xoebus** [comment]
This should be possible with this: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#routes

Please re-open if this is not the case.
