### ISSUE TITLE
Using with Travis?

### ISSUE THREAD

**Issue by Snugug** [contraband/autopilot#16]
I'd love to use this plugin with Travis, but I can't seem to get Travis to reliably install the plugin and use it through their deploy process. Do you have instructions for using it with Travis?

Thanks!

**Comment by rafael-nogueras** [comment]
@Snugug I haven't tried this myself --so your mileage may vary!-- but I was shown the following `.travis.yml` as an example of a project that is using Autopilot with Travis CI using a `script` provider: https://github.com/18F/epa-notice/blob/master/.travis.yml#L19-L27

**Comment by xoebus** [comment]
Thanks for the issue!

Let's track this in that issue instead. It's on their end if they want to include `autopilot`.
