### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by matthewford** [contraband/autopilot#28]
Hello,

I'm having some trouble installing the plugin 
matt@Matt-BZC001 ~/Downloads> cf install-plugin autopilot-darwin 

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin autopilot-darwin? (y or n)> y

Installing plugin ./autopilot-darwin...
FAILED
fork/exec ./autopilot-darwin: permission denied

This was fixed by running: `chmod +x autopilot-darwin`

**Comment by xoebus** [comment]
Thanks for the issue. I've added more explicit instructions to the README.
