### ISSUE TITLE
CF_TRACE=true causes b0rk on Windows

### ISSUE THREAD

**Issue by DanielJonesEB** [contraband/autopilot#31]
With a customer using the plugin, and when `CF_TRACE` was set to `true` after the 200 OK from the initial push, there was an "unexpected end of JSON" error. Was only fleeting and I'm supposed to be pairing with the chap now, so will investigate more later if I get time.

**Comment by xoebus** [comment]
Probably because [this line](https://github.com/contraband/autopilot/blob/master/autopilot.go#L190) returns that output too. I'm going to cowardly claim that this is a CLI bug and to bring it up with them.

Maybe it's fixed in a newer version of the CLI library we compile against?
