### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by alkalinecoffee** [contraband/autopilot#36]
Can we get a new version published?  It's been almost a year since 0.0.2 was released, and there are a few updates merged in since then that would help my team.

Thanks and great work on this!

**Comment by xoebus** [comment]
Done! Sorry for the huge delay. 😞

**Comment by maniax89** [comment]
Can we publish this to the https://plugins.cloudfoundry.org/ so that it can be installed with `cf install-plugin -r CF-Community "autopilot"` ?

**Comment by adborden** [comment]
Should I open a new issue to get this on plugins.cloudfoundry.org?

**Comment by xoebus** [comment]
Nope, this issue is fine. I'll try and find the time to publish it there.

**Comment by xoebus** [comment]
Thanks for your patience! Once this gets merged it will be available.

https://github.com/cloudfoundry/cli-plugin-repo/pull/193
