### ISSUE TITLE
Tail cf logs during staging

### ISSUE THREAD

**Issue by JohannesRudolph** [contraband/autopilot#38]
Please see the attached issue: https://github.com/concourse/cf-resource/issues/28

I think this may be possibly addressed in autopilot, although I think it may be asking the tool to do too much and it should instead be left to an upstream task. But then again, autopilot is already effectively just an orchestrator for other primitive CF commands. Thoughts?

**Comment by aeijdenberg** [comment]
Although the PR linked above is closed, we added this in another [commit](https://github.com/contraband/autopilot/commit/aea62a36913e6223d0e7959462981c3bfee0886f) which landed earlier today, so passing a parameter of `--show-app-log` should now work.

**Comment by JohannesRudolph** [comment]
This is great stuff! thanks @aeijdenberg !
